### ISSUE TITLE
Sidebar menu not visible if page scrolled

### ISSUE THREAD

**Issue by babsonmatt** [GroundXaero/bootstrap-easy-sidebar#3]
If you toggle the sidebar while the page is scrolled down, the sidebar contents is no longer visible (assuming the height of the contents is less than the amount the page has scrolled down).

**Comment by AndyCormack** [comment]
Can you elaborate a bit more? I'm not entirely sure what you mean. The menu is always positioned to the top of the page if that's what you mean.

**Comment by babsonmatt** [comment]
I'm using Chrome Version 43.0.2342.2 dev-m (64-bit)

1.) Scroll down vertically on a page
2.) Trigger the sidebar to open
3.) The sidebar contents will be off the screen

Shouldn't the sidebar position be fixed, so regardless of scroll position of the body the sidebar nav is always visible? If not, I'd need to scroll to the top of the page to view the nav, every time I toggled it.

Hopefully that helps, thanks for the quick reply!

EDIT: http://i.imgur.com/sf2ufjc.png

**Comment by AndyCormack** [comment]
Yea I get ya. I originally designed the menu you be toggled by a button on the page so I made the mistake of _assuming_ people would just chuck a button at the top.

Then it evolved into the mobile friendly swipe version and now it probably makes more sense to have it fixed instead. I'll change it tomorrow if I get the time.

**Comment by babsonmatt** [comment]
Gotcha, appreciate it.

**Comment by AndyCormack** [comment]
This should now be fixed in the new v1.2.0 release.

Let me know if there are any bugs / fixes / browser compatibility issues as I've had little time to test outside of chrome.
