### ISSUE TITLE
JavaScript file

### ISSUE THREAD

**Issue by rougin** [GroundXaero/bootstrap-easy-sidebar#4]
Hello! This is a good solution for integrating sidebars for Bootstrap but can you include a JavaScript file to your library? In order to save time in installing it. :smile:

**Comment by AndyCormack** [comment]
I prefer not to include others work in my own unless I have to in order to not get version frozen with when I developed this. If you install Bower you can download all of it with dependencies much more easily http://bower.io/

**Comment by rougin** [comment]
I mean include the _small script_ found in the **Usage** section in a JavaScript file for user's convenience.

**Comment by AndyCormack** [comment]
Yes, and I explained my reason for not doing that above. Bower is so much easier, github unfortunately does not download dependencies in the zip. Just install bower and type the command in your command prompt
`bower install bootstrap-easy-sidebar`
This will download my sidebar plus the required dependency without any hassle. :)
